TradingSim/API/urls.py
from django.urls import path
from .views import *
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

urlpatterns = [
    path("CR-buy-orders", buy_orders),
    path("CR-sell-orders", sell_orders),
    path("CR-portfolios", user_portfolios),
    path("RUD-buy-order/<int:id>", buy_order_by_id),
    path("RUD-sell-order/<int:id>", sell_order_by_id),
    path("RUD-portfolio/<str:user>", portfolio_by_username),
]

urlpatterns = format_suffix_patterns(urlpatterns)

TradingSim/LeaderboardApp/urls.py
from django.urls import path
from .views import leaderboard_view

app_name = "leaderboard"

urlpatterns = [
    path("", leaderboard_view, name="leaderboard-view")
]

TradingSim/TickerApp/urls.py
from django.urls import path
from .views import *

app_name = 'ticker'

urlpatterns = [
    path("", get_ticker, name="get-ticker"),
    path("display-ticker-info/", display_ticker_info, name="ticker-info"),
    path("incorrect-ticker", incorrect_ticker, name="incorrect-ticker")
]
# router for Ticker App

TradingSim/TradingSim/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from TradingSim.views import *
from TickerApp import urls
from UsersApp import urls
from OrdersApp import urls
from LeaderboardApp import urls
from API import urls

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("", home, name="home"),
    path("info/", info, name="info"),
    path("ticker/", include('TickerApp.urls')),
    path("user/", include('UsersApp.urls')),
    path("order/", include('OrdersApp.urls')),
    path("leaderboard/", include("LeaderboardApp.urls")),
    path("api/", include('API.urls')),
    re_path(r".*", page_not_found, name="404")
]
# master router for the project

TradingSim/UsersApp/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path("signup/", signup_user, name="signup"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("delete-account/", delete_account, name="delete-account")
]
# router for Users App

TradingSim/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>
          {% block title%}
              DayTradeSim
          {% endblock %}
      </title>
      {% block links %}
        PLACEHOLDER
      {% endblock links %}
  </head>
  <body>
    {% block navbar %}
    PLACEHOLDER
    {% endblock navbar %}
    
    {% block content%}
    Add content here
    {% endblock%}

    {% block confirmationModal %}
    
    {% endblock confirmationModal %}

    {% block loadingElement %}
      PLACEHOLDER
    {% endblock loadingElement %}
  </body>
</html>
{% comment %} base -> navbar -> modals -> layout {% endcomment %}

TradingSim/templates/layouts/layout.html
{% extends 'layouts/modals.html' %}

{% block links %}
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'styles/general.css' %}">
    <script src="{% static 'scripts/quick_loading_graphic_trig.js' %}"></script>
    <script src="{% static 'scripts/unload_graphic_trig.js' %}"></script>
{% endblock links %}

{% comment %} base -> navbar -> modals -> layout {% endcomment %}

TradingSim/templates/layouts/modals.html
{% extends "layouts/navbar.html" %}

{% block confirmationModal %}
    <div class="modal fade confirmation-modal" id="confirmModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog">
            {% block imageToggle %}
                <div class="modal-content border">
                    <div class="modal-header bg-dark">
                    <h1 class="modal-title fs-5 bg-dark text-white">Are You Sure?</h1>
                    <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close" id="closeModalXBtn"></button>
                </div>
            <div class="modal-body bg-dark text-white">
                {% block modalBody %}
                    There is no going back after selecting "yes"
                {% endblock modalBody %}
            </div>
            <div class="modal-footer bg-dark text-white">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="submitButton">yes</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="closeModalNoBtn">No</button>
            </div>
        </div>
        {% endblock imageToggle %}
        </div>
    </div>
{% endblock confirmationModal %}

{% block loadingElement %}
    <div class="invisible d-flex justify-content-center" id="loadingGraphic" tabindex="-1" aria-hidden="true">
        <div class="spinner-border text-success loading-graphic" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
{% endblock loadingElement %}

{% comment %} base -> navbar -> modals -> layout {% endcomment %}

TradingSim/templates/layouts/navbar.html
{% extends 'layouts/base.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account Management
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'user:logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                  <button class="navbar-button">
                    <a class="nav-link active" aria-current="page" href="{% url 'user:delete-account' %}">Delete Account</a>
                  </button>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:signup' %}">Sign Up</a>
                </li>
              {% endif %}
            </ul>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'info' %}">Info</a>
            </li>
          <li class="nav-item">
            <a class="nav-link"href="{% url 'ticker:get-ticker' %}">Ticker Search</a>
          </li>
          <li class="nav-item">
            <a class="nav-link"href="{% url 'leaderboard:leaderboard-view' %}">Leaderboard</a>
          </li>
          <li class="nav-item">
            <span style="font-size: 30px;" class="navbar-text">|</span>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item text-white">
            <a class="nav-link" href="">Username: {{ user.username }}</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'ticker:ticker-info' %}" method="post">
          {% csrf_token %}
          <input class="form-control me-2" type="text" name="ticker" placeholder="Quick Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit" id="quickLoadModalTrigger">Search</button>
        </form>
      </div>
    </div>
  </nav>
{% endblock navbar %}

{% comment %} base -> navbar -> modals -> layout {% endcomment %}

TradingSim/templates/layouts/navbar_layout.html
{% extends 'layouts/base_layout.html' %}

{% block navbar %}
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Account Management
            </a>
            <ul class="dropdown-menu">
              {% if user.is_authenticated %}
                <li class="nav-item">
                  <form action="{% url 'user:logout' %}" method="POST">
                    <button class="logout-button">
                      <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Log Out</a>
                    </button>
                  </form>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:delete-account' %}">Delete Account</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'user:signup' %}">Sign Up</a>
                </li>
              {% endif %}
            </ul>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ticker:get-ticker' %}">Ticker Search</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'ticker:ticker-info' %}" method="post">
          {% csrf_token %}
          <input class="form-control me-2" type="text" name="ticker" placeholder="Quick Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit" id="quickLoadModalTrigger">Search</button>
        </form>
      </div>
    </div>
  </nav>
{% endblock navbar %}