TradingSim/API/urls.py
from django.urls import path
from .views import *
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

urlpatterns = [
    path("CR-buy-orders", buy_orders),
    path("CR-sell-orders", sell_orders),
    path("CR-portfolios", user_portfolios),
    path("RUD-buy-order/<int:id>", buy_order_by_id),
    path("RUD-sell-order/<int:id>", sell_order_by_id),
    path("RUD-portfolio/<str:user>", portfolio_by_username),
]

urlpatterns = format_suffix_patterns(urlpatterns)

TradingSim/OrdersApp/urls.py
from django.urls import path
from .views import *

app_name = "order"

urlpatterns = [
    path("buy-order/", place_buy_order, name="buy-order"),
    path("sell-order/", place_sell_order, name="sell-order"),
    path("insufficient-funds/", insufficient_funds, name="insufficient-funds"),
    path("buy/<slug:id>", buy_order_details, name="buy-order-details"),
    path("sell/<slug:id>", sell_order_details, name="sell-order-details"),
]
# router for Orders App

TradingSim/TradingSim/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from TradingSim.views import *
from TickerApp import urls
from UsersApp import urls
from OrdersApp import urls
from LeaderboardApp import urls
from API import urls

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("", home, name="home"),
    path("info/", info, name="info"),
    path("ticker/", include('TickerApp.urls')),
    path("user/", include('UsersApp.urls')),
    path("order/", include('OrdersApp.urls')),
    path("leaderboard/", include("LeaderboardApp.urls")),
    path("api/", include('API.urls')),
    re_path(r".*", page_not_found, name="404")
]
# master router for the project

TradingSim/templates/home.html
{% extends 'layouts/layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block imageToggle %}
{% load static %}
<div class="d-flex container justify-content-center">
    <img src="{% static 'assets/userStats/profitReport.png' %}" alt="">
</div>
{% endblock imageToggle %}

{% block content %}
{% if user.is_authenticated %}
<div class="d-flex container justify-content-center">
    <h1 class='text-center'>Trading Stats</h1>
</div>
<div class="d-flex container justify-content-center">
    <table style="width:90%" class="table table-dark table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">Total Profit So Far</th>
            <th class="text-center" scope="col">Highest Profit In One Sale</th>
            <th class="text-center"scope="col">Average Profit Per Sale</th>
            <th class="text-center"scope="col">Average buy/sell Cycle In Days</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th class="text-center">{{ stats.total_profit }}</th>
            <th class="text-center">{{ stats.max_profit }}</th>
            <th class="text-center">{{ stats.avg_profit }}</th>
            <th class="text-center">{{ stats.avg_buy_sell_duration }}</th>
        </tr>
        </tbody>
    </table>
</div>

<div class="d-flex container justify-content-center">
    <h1 class='text-center'>Portfolio</h1>
</div>
<div class="d-flex container justify-content-center">
    <table  style="width:90%" class="table table-dark table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">Portfolio Total</th>
            <th class="text-center" scope="col">Liquid</th>
            <th class="text-center" scope="col">Invested</th>
            <th class="text-center" scope="col">Liquid %</th>
            <th class="text-center" scope="col">Invested %</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th class="text-center">{{ stats.total_portfolio }}</th>
            <th class="text-center">{{ stats.liquid_portfolio }}</th>
            <th class="text-center">{{ stats.invested_portfolio }}</th>
            <th class="text-center">{{ stats.liquid_percent }}</th>
            <th class="text-center">{{ stats.invested_percent }}</th>
        </tr>
        </tbody>
    </table>
</div>

<div class="d-flex container justify-content-center">
    <h1 class='text-center'>Current Floating Buy Orders</h1>
</div>
<div class="d-flex container justify-content-center">
    <table style="width:75%" class="table table-dark table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th class="text-center" scope="col">Ticker</th>
            <th class="text-center" scope="col">Date</th>
            <th class="text-center" scope="col">Stock Amount</th>
            <th class="text-center" scope="col">% of Portfolio</th>
        </tr>
        </thead>
        <tbody>
            {% for buy_order in stats.buy_orders %}
            <tr>
                <td class="text-center">
                    <a href="{% url 'order:buy-order-details' id=buy_order.id %}">{{ buy_order.id }}</a>
                </td>
                <td class="text-center">
                    {{ buy_order.ticker }}
                </td>
                <td class="text-center">
                    {{ buy_order.buyDate }}
                </td>
                <td class="text-center">
                    {{ buy_order.stockAmount }}
                </td>
                <td class="text-center">
                    {{ buy_order.totalPercentage }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="d-flex container justify-content-center">
    <h1 class='text-center'>Completed Sell Orders</h1>
</div>
<div class="d-flex container justify-content-center">
    <table style="width:75%" class="table table-dark table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th class="text-center" scope="col">Ticker</th>
            <th class="text-center"scope="col">Buy Date</th>
            <th class="text-center" scope="col">Sell Date</th>
            <th class="text-center" scope="col">Stock Amount</th>
            <th class="text-center" scope="col">% of Total Profit</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            {% for sell_order in stats.sell_orders %}
            <tr>
                <td class="text-center">
                    <a href="{% url 'order:sell-order-details' id=sell_order.id %}">{{ sell_order.id }}</a>
                </td>
                <td class="text-center">
                    {{ sell_order.ticker }}
                </td>
                <td class="text-center">
                    {{ sell_order.buyDate }}
                </td>
                <td class="text-center">
                    {{ sell_order.sellDate }}
                </td>
                <td class="text-center">
                    {{ sell_order.stockAmount }}
                </td>
                <td class="text-center">
                    {{ sell_order.totalPercentage }}
                </td>
            </tr>
            {% endfor %}
        </tr>
        </tbody>
    </table>
</div>

<div class="d-flex container justify-content-center">
    <a class="btn btn-success btn-lg mx-5" href="{% url 'order:buy-order' %}">Buy Order</a>
    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#confirmModal">Display Profit Report</button>
    <a class="btn btn-success btn-lg mx-5" href="{% url 'order:sell-order' %}">Sell Order</a>
</div>
{% else %}
<h1 class="text-center">Please log in to view the home page</h1>
{% endif %}
{% endblock content %}

TradingSim/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
    <form action="/home" method="post">
        <label for=""></label>
    </form>
</body>

</html>

TradingSim/templates/info.html
{% extends 'layouts/layout.html' %}

{% block title %}
    Info
{% endblock title %}

{% block content %}

<div class="container">
    <div class="d-flex justify-content-center">
        <h1>Info</h1>
    </div>
    <div class="d-flex justify-content-center">
        <h3>Overview</h3>
    </div>
    <div class="d-flex row justify-content-center">
        <p class="col border border-2 border-secondary fs-5">This website will allow you to create an account, and trade stocks and ETF's using fake money, but with real time data.</p>
        <p class="col border border-2 border-secondary fs-5">In the future There will be an API endpoint to allow you to remotely and automatically perform operations with the site.</p>
        <p class="col border border-2 border-secondary fs-5">The purpose of this site is to help people refine their day trading skills with absolutely zero risk</p>
    </div>
    <div class="d-flex justify-content-center">
        <h3>Usage guide</h3>
    </div>
    <div class="d-flex row justify-content-center">
        <div class="row">
            <p class="col border border-2 border-secondary fs-5">You will need to create an account before you can access the full functionality of the page</p>
            <p class="col border border-2 border-secondary fs-5">You can find the sign up button underneath the Account Management dropdown in the navbar</p>
            <p class="col border border-2 border-secondary fs-5">Each new account will be given 25,000 dollars to trade with as that complies with the PDT rule</p>
            <p class="col border border-2 border-secondary fs-5">You can use quick search or Ticker Search to look up current information about a stock that was scraped from Yahoo Finance</p>
            <p class="col border border-2 border-secondary fs-5">In the home page when you are logged in you will see two buttons, buy order and sell order</p>
            <p class="col border border-2 border-secondary fs-5">The Buy Order button will take you to the page needed for you to fill out a buy order form</p>
        </div>
        <div class="row">
            <p class="col border border-2 border-secondary fs-5">The Sell Order button will take you to the page needed for you to fill out a sell order form, after completing this action your profit will be calculated</p>
            <p class="col border border-2 border-secondary fs-5">The Buy Order form has 3 inputs, ticker, stock amount and sell trigger</p>
            <p class="col border border-2 border-secondary fs-5">ticker is the stock ticker of the stock you want to buy</p>
            <p class="col border border-2 border-secondary fs-5">stock amount is the amount of stocks you want to purchase (the amount of money you spend will be the stock amount times the current price)</p>
            <p class="col border border-2 border-secondary fs-5">the sell trigger is the amount you want to sell the stock at, this will be done automatically for you when the stock reaches that price</p>
        </div>
    </div>

    <h3>Learn More: <i><a href="https://www.investopedia.com/">Investopedia.com</a></i></h3>
</div>
{% endblock content %}

TradingSim/templates/log-in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="/home" method="post">
        <label for="username">Username: </label>
        <input type="text" id="username" name="username">

        <label for="username">Password: </label>
        <input type="password" id="username" name="username">
    </form>
</body>
</html>

TradingSim/templates/page-not-found.html
{% extends "layouts/layout.html" %}

{% block content %}
    <h1 class="text-center">404</h1>
    <h2 class="text-center">The page you're looking for does not exist</h2>
{% endblock content %}