TradingSim/API/urls.py
from django.urls import path
from .views import *
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

urlpatterns = [
    path("CR-buy-orders", buy_orders),
    path("CR-sell-orders", sell_orders),
    path("CR-portfolios", user_portfolios),
    path("RUD-buy-order/<int:id>", buy_order_by_id),
    path("RUD-sell-order/<int:id>", sell_order_by_id),
    path("RUD-portfolio/<str:user>", portfolio_by_username),
]

urlpatterns = format_suffix_patterns(urlpatterns)

TradingSim/OrdersApp/urls.py
from django.urls import path
from .views import *

app_name = "order"

urlpatterns = [
    path("buy-order/", place_buy_order, name="buy-order"),
    path("sell-order/", place_sell_order, name="sell-order"),
    path("insufficient-funds/", insufficient_funds, name="insufficient-funds"),
    path("buy/<slug:id>", buy_order_details, name="buy-order-details"),
    path("sell/<slug:id>", sell_order_details, name="sell-order-details"),
]
# router for Orders App

TradingSim/TradingSim/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from django.conf import settings
from TradingSim.views import *
from TickerApp import urls
from UsersApp import urls
from OrdersApp import urls
from LeaderboardApp import urls
from API import urls

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path("", home, name="home"),
    path("info/", info, name="info"),
    path("ticker/", include('TickerApp.urls')),
    path("user/", include('UsersApp.urls')),
    path("order/", include('OrdersApp.urls')),
    path("leaderboard/", include("LeaderboardApp.urls")),
    path("api/", include('API.urls')),
    re_path(r".*", page_not_found, name="404")
]
# master router for the project

TradingSim/OrdersApp/models.py
from django.db import models

# Create your models here.
class BuyOrders(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.CharField(max_length=50)
    ticker = models.CharField(max_length=5)
    buyPrice = models.FloatField()
    cashAmount = models.FloatField()
    stockAmount = models.FloatField()
    buyDate = models.DateField()
    totalPercentage = None

    def __str__(self):
        return f"{self.user} bought {self.stockAmount} shares of {self.ticker} for {self.cashAmount}"


class SellOrders(models.Model):
    id = models.IntegerField(primary_key=True)
    user = models.CharField(max_length=50)
    ticker = models.CharField(max_length=5)
    buyPrice = models.FloatField()
    cashAmount = models.FloatField()
    stockAmount = models.FloatField()
    sellPrice = models.FloatField()
    profit = models.FloatField()
    buyDate = models.DateField(default="1950-1-1")
    sellDate = models.DateField(default="1950-1-1")
    totalPercentage = None

    def __str__(self):
        return f"{self.user} sold {self.stockAmount} shares of {self.ticker} for {self.profit} profit"

'''
    CurrentMarketOrders schema:
    orderID: auto incrementing Primary key of CurrentMarketOrders model
    user: get the current user and add that value automatically to this row
    ticker: get the ticker symbol that they inputted in the form to place the order
    buyprice: the price that the stock was bought at
    cashAmount: will be a float storing the cash amount used to purchase the stocks
    stockAmount: will be a float storing the amount of stocks the order gained the user
    sellTrigger: will be a float storing the price at which the user will automatically sell the stock
    buydate: the date the order was placed on to assist with data vis for user

    CompleteMarketOrders schema:
    orderID: data will be transferred from user field of CurrentMarketOrders upon transfer
    user: data will be transferred from user field of CurrentMarketOrders upon transfer
    ticker: data will be transferred from user field of CurrentMarketOrders upon transfer
    buyprice: data will be transferred from user field of CurrentMarketOrders upon transfer
    cashAmount: data will be transferred from user field of CurrentMarketOrders upon transfer
    stockAmount: data will be transferred from user field of CurrentMarketOrders upon transfer
    sellprice: sell price will be set whenever the user puts in a sell order
    profit: will be an aggregate value of (sellprice * stockAmount) - cashAmount
    buyDate: data will be transferred from user field of CurrentMarketOrders upon transfer
    sellDate: will be a date value set by whatever the date is either when the stock price first hit the sell trigger, or when the stock is manually sold

'''

TradingSim/OrdersApp/views.py
from django.shortcuts import render, redirect
from .models import BuyOrders, SellOrders
from .handlers import handle_buy_order, handle_sell_order
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url="/user/login")
def place_buy_order(request):
    return handle_buy_order(request)
    # logic abstracted out to handlers.py to decrease repetition
    # This logic is also used in the REST API
    # I kept the view function structure in place to maintain a pattern and make the code more coherent
    
@login_required(login_url="/user/login")
def place_sell_order(request):
    return handle_sell_order(request)
    # logic abstracted out to handlers.py to decrease repetition
    # This logic is also used in the REST API
    # I kept the view function structure in place to maintain a pattern and make the code more coherent

def sell_order_details(request, id):
    order = SellOrders.objects.get(id=id)

    order.buyPrice = round(order.buyPrice, 2)
    order.cashAmount = round(order.cashAmount, 2)

    return render(request, "sell-order-details.html", {"order": order})

def buy_order_details(request, id):

    order = BuyOrders.objects.get(id=id)

    return render(request, "buy-order-details.html", {"order": order})

def insufficient_funds(request):
    return render(request, "insufficient-funds.html")

TradingSim/OrdersApp/templates/buy-order-details.html
{% extends 'layouts/layout.html' %}

{% block content %}
<div class="d-flex container justify-content-center">
    <table style="width:75%" class="table table-dark table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th class="text-center" scope="col">User</th>
            <th class="text-center" scope="col">Ticker</th>
            <th class="text-center" scope="col">Buy Price</th>
            <th class="text-center" scope="col">Cash Amount</th>
            <th class="text-center" scope="col">Stock Amount</th>
            <th class="text-center" scope="col">Buy Date</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">
                    {{ order.id }}
                </td>
                <td class="text-center">
                    {{ order.user }}
                </td>
                <td class="text-center">
                    {{ order.ticker }}
                </td>
                <td class="text-center">
                    {{ order.buyPrice }}
                </td>
                <td class="text-center">
                    {{ order.cashAmount }}
                </td>
                <td class="text-center">
                    {{ order.stockAmount }}
                </td>
                <td class="text-center">
                    {{ order.buyDate }}
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content %}

TradingSim/OrdersApp/templates/insufficient-funds.html
{% extends 'layouts/layout.html' %}

{% block content %}
    <h1 class="text-center">Sorry, it doesn't seem like you have enough money in your account...</h1>
    <h3 class="text-center">You're broke, but not really?</h3>
{% endblock content %}

TradingSim/OrdersApp/templates/order-details.html
{% extends 'layouts/layout.html' %}

{% block content %}
    <h3>ID: {{ order.id }}</h3>
    <h3>user: {{ order.user }}</h3>
    <h3>ticker: {{ order.ticker }}</h3>
    <h3>Buy Price: {{ order.buyprice }}</h3>
    <h3>Cash Amount: {{ order.cashAmount }}</h3>
    <h3>Stock Amount: {{ order.stockAmount }}</h3>
    <h3>Sell Trigger: {{ order.sellTrigger }}</h3>
    <h3>Pending: {{ order.pending }}</h3>
    <h3>Buy Date: {{ order.buydate }}</h3>
{% endblock content %}

TradingSim/OrdersApp/templates/place-buy-order.html
{% extends 'layouts/layout.html' %}

{% block modalBody %}
    Your current portfolio is: {{ portfolio.totalPortfolioAmount }}
{% endblock modalBody %}

{% block confirmBtnContent %}
    Yes
{% endblock confirmBtnContent %}

{% block content %}

    {% load static %}
    <script src="{% static 'scripts/loading_graphic_trig.js' %}"></script>
    <script src="{% static 'scripts/modal_submit.js' %}"></script>

    <h1 class="text-center">Place a Buy Order</h1>
    <form action="{% url 'order:buy-order' %}" method="post" id="order-form" class="d-flex justify-content-center">
        <input type="hidden" name="username" value="{{ user.username }}">

        <input type="text" name="ticker" placeholder="Ticker" required><br>

        <input type="text" name="stockAmount" placeholder="Stock Amount" required><br>

        <button type="button" class="btn btn-success" id="loadModalTrigger" data-bs-toggle="modal" data-bs-target="#confirmModal">Submit</button>
    </form>
{% endblock content %}

TradingSim/OrdersApp/templates/place-sell-order.html
{% extends 'layouts/layout.html' %}

{% block modalBody %}
    Your current portfolio is: {{ portfolio.totalPortfolioAmount }}
{% endblock modalBody %}

{% block confirmBtnContent %}
    Yes
{% endblock confirmBtnContent %}

{% block content %}

    {% load static %}
    <script src="{% static 'scripts/loading_graphic_trig.js' %}"></script>
    <script src="{% static 'scripts/modal_submit.js' %}"></script>

    <h1 class="text-center">Place a Sell Order</h1>
    <div class="d-flex justify-content-center">
        <form action="{% url 'order:sell-order'%}" method="post" id="order-form" class="d-flex justify-content-center">
            <div class="row">
                <input type="text" name="id" style="width:70%" placeholder="Order ID" required>
            </div>
    
            <button type="button" class="btn btn-success row" id="loadModalTrigger" data-bs-toggle="modal" data-bs-target="#confirmModal">Submit</button>
        </form>
    </div>
    <h3 class="text-center">Order Stubs For {{ user.username }}</h3>

    <div class="d-flex container justify-content-center">
        <table style="width:75%" class="table table-dark table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th class="text-center" scope="col">ID</th>
                <th class="text-center" scope="col">Buy Date</th>
                <th class="text-center" scope="col">Ticker</th>
                <th class="text-center" scope="col">Stock Amount</th>
            </tr>
            </thead>
            <tbody>
                {% for order in currentOrders %}
                <tr>
                    <td>
                        <a href="{% url 'order:buy-order-details' id=order.id %}">{{ order.id }}</a>
                    </td>
                    <td>
                        {{ order.buyDate }}
                    </td>
                    <td>
                        {{ order.ticker }}
                    </td>
                    <td>
                        {{ order.stockAmount }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

TradingSim/OrdersApp/templates/sell-order-details.html
{% extends 'layouts/layout.html' %}

{% block content %}
<div class="d-flex container justify-content-center">
    <table style="width:75%" class="table table-dark table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th class="text-center" scope="col">ID</th>
            <th class="text-center" scope="col">User</th>
            <th class="text-center" scope="col">Ticker</th>
            <th class="text-center" scope="col">Buy Price</th>
            <th class="text-center" scope="col">Cash Amount</th>
            <th class="text-center" scope="col">Stock Amount</th>
            <th class="text-center" scope="col">Sell Price</th>
            <th class="text-center" scope="col">Profit</th>
            <th class="text-center" scope="col">Buy Date</th>
            <th class="text-center" scope="col">Sell Date</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-center">
                    {{ order.id }}
                </td>
                <td class="text-center">
                    {{ order.user }}
                </td>
                <td class="text-center">
                    {{ order.ticker }}
                </td>
                <td class="text-center">
                    {{ order.buyPrice }}
                </td>
                <td class="text-center">
                    {{ order.cashAmount }}
                </td>
                <td class="text-center">
                    {{ order.stockAmount }}
                </td>
                <td class="text-center">
                    {{ order.sellPrice }}
                </td>
                <td class="text-center">
                    {{ order.profit }}
                </td>
                <td class="text-center">
                    {{ order.buyDate }}
                </td>
                <td class="text-center">
                    {{ order.sellDate }}
                </td>
            </tr>
        </tbody>
    </table>
</div>
{% endblock content %}